
export class OpcionesDeCredito  {
  plazo : number                              // 60,
  periodoPlazo : string                       // "D",
  periodicidadPlazo : string                  // "M",
  montoFinanciado : number                    //  299.17,
  valorARecibir : number                      // 264.72,
  valorAPagar : number                        // 0.0,
  costoCustodia : number                      // 15.41,
  costoFideicomiso : number                   // 1.68,
  costoSeguro : number                        // 0.16,
  costoTasacion : number                      // 16.95,
  costoTransporte : number                    // 0.0,
  costoValoracion : number                    // 0.0,
  impuestoSolca : number                      // 0.25,
  formaPagoImpuestoSolca : string             // "C",
  formaPagoCapital : string                   // "C",
  formaPagoCustodia : string                  // "C",
  formaPagoFideicomiso : string               // "C",
  formaPagoInteres : string                   // "C",
  formaPagoMora : string                      // "C",
  formaPagoGastoCobranza : string             // "C",
  formaPagoSeguro : string                    // "C",
  formaPagoTasador : string                   // "C",
  formaPagoTransporte : string                // "C",
  formaPagoValoracion : string                // "C",
  saldoInteres : number                       // 0.0,
  saldoMora : number                          // 0.0,
  gastoCobranza : number                      // 0.0,
  cuota : number                              // 307.18,
  saldoCapitalRenov : number                  // 0.0,
  montoPrevioDesembolso : number              // 0.0,
  totalGastosNuevaOperacion : number              // 34.2,
  totalCostosOperacionAnterior : number           // 0.0,
  custodiaDevengada : number                      // 0.0,
  formaPagoCustodiaDevengada : string             // "C",
  tipooferta : string                             // "N",
  porcentajeflujoplaneado : number                // 0,
  dividendoflujoplaneado : number                 // 999,
  dividendosprorrateoserviciosdiferido : number   // 0
  constructor(){}
}