export enum CanalContactoEnum{
    BUSES = "BUSES",
    CALL_CENTER = "CALL CENTER",
    FLYERS = "FLYERS",
    PAGINA_WEB = "PAGINA WEB",
    RADIO = "RADIO",
    REDES_SOCIALES = "REDES SOCIALES",
    REFERIDO = "REFERIDO",
    REFERIDO_MUPI = "REFERIDO MUPI",
    TELEFONO = "TELEFONO",
    TELEVISION = "TELEVISION",
    VALLAS = "VALLAS",
    VENTA_EXTERNA = "VENTA EXTERNA"
}