export enum EstadoAprobacionEnum {
    NIVEL_UNO= 'NIVEL_UNO',
    NIVEL_DOS= 'NIVEL_DOS',
    NIVEL_TRES= 'NIVEL_TRES',
    APROBADO= 'APROBADO',
    NEGADO= 'NEGADO',
    PENDIENTE_APROBACION='PENDIENTE_APROBACION',
    FINALIZADO='FINALIZADO',
    DISPONIBLE='DISPONIBLE',
    EN_EJECUCION='EN_EJECUCION'
}
