export enum EstadoContratoEnum{
    ADQUIRIDO="ADQUIRIDO",
	PENDIENTE_HABILITANTE="PENDIENTE_HABILITANTE",
	VIGENTE="VIGENTE",
	PERFECCIONADO="PERFECCIONADO",
	CANCELADO="CANCELADO",
	RENOVADO="RENOVADO",
	ENTREGA_CUSTODIO="ENTREGA_CUSTODIO",
	RENOVADO_ADENDUM="RENOVADO_ADENDUM",
	VIGENTE_ADENDUM="VIGENTE_ADENDUM"
}