export enum EstadoJoyaEnum{
    COTIZADO="COTIZADO",
	CUSTODIA="CUSTODIA",
	PERFECCIONADO="PERFECCIONADO",
	EXISTENCIA_LOTE="EXISTENCIA_LOTE",
	EXISTENCIA_VITRINA="EXISTENCIA_VITRINA",
	RETAZADA_VITRINA="RETAZADA_VITRINA",
	RETAZADA_LOTE="RETAZADA_LOTE",
	EXISTENCIA="EXISTENCIA",
	VENDIDA="VENDIDA",
	DEVUELTA="DEVUELTA",
	CANCELADA="CANCELADA",
	PENDIENTE_HABILITANTE="PENDIENTE_HABILITANTE",	
	VENDIDA_VITRINA="VENDIDA_VITRINA",
	VENDIDA_LOTE="VENDIDA_LOTE"
}