export enum EstadoQuskiEnum{
    ACT="ACT",
    INA="INA",
    PENDIENTE="PENDIENTE",
    PAGADO="PAGADO",
    VIGENTE="VIGENTE",
	CREADO="CREADO",
	CERRADO="CERRADO",
    PENDIENTE_HABILITANTE="PENDIENTE_HABILITANTE",
    VENDIDO="VENDIDO"
}