export enum MotivoDesestimientoEnum{
    MUY_CARO = "MUY_CARO",
    NO_LE_DAN_EL_MONTO_QUE_NECESITA='NO_LE_DAN_EL_MONTO_QUE_NECESITA',
    NO_LE_GUSTO_EL_PRODUCTO='NO_LE_GUSTO_EL_PRODUCTO',
    NO_LE_GUSTO_LA_ATENCION='NO_LE_GUSTO_LA_ATENCION'
}