export enum ObservacionTrackingEnum {
    // Tareas relacionadas a gestion cliente
    // REGISTRO_DE_INFORMACION_DEL_CLIENTE = "REGISTRO DE INFORMACION DEL CLIENTE",
    // REGISTRO_DE_DOCUMENTOS_DEL_CLIENTE = "REGISTRO DE DOCUMENTOS DEL CLIENTE",
    // PRESENTAR_DATOS_DE_CLIENTE_EXISTENTE = "PRESENTAR DATOS DE CLIENTE EXISTENTE",
    // CALCULO_DE_NIVEL_DE_ENDEUDAMIENTO_EN_INGRESOS_Y_EGRESOS = "CALCULO DE NIVEL DE ENDEUDAMIENTO EN_INGRESOS Y EGRESOS",
    // CALCULO_DE_PATRIMONIO_DEL_CLIENTE = "CALCULO DE PATRIMONIO DEL CLIENTE",
    // AGREGANDO_REFERENCIAS_PERSONALES_DEL_CLIENTE = "AGREGANDO REFERENCIAS PERSONALES DEL CLIENTE",
    
    
}