export enum OrigenIngresosEnum{
    EMPLEADO_PRIVADO = 'EMPLEADO PRIVADO',
    EMPLEADO_PUBLICO = 'EMPLEADO PÚBLICO',
    AMA_CASA = 'AMA DE CASA',
    JUBILADO = 'JUBILADO',
    REMESAS = 'REMESAS',
    RENTISTAS = 'RENTISTAS'
}