export enum ProcesoEnum {
  COMPRA_DIRECTA = "COMPRA_DIRECTA",
  COMPRA_PLAZO = "COMPRA_PLAZO",
  CARGA_HABILITANTES = "CARGA_HABILITANTES",
  PERFECCIONAMIENTO = "PERFECCIONAMIENTO",
  CANCELAR_CONTRATO = "CANCELAR_CONTRATO",
  RENOVAR_CONTRATO = "RENOVAR_CONTRATO",
  RETASACION_LOTE = "RETASACION_LOTE",
  RETASACION_VITRINA = "RETASACION_VITRINA",
  VENTA_LOTE = "VENTA_LOTE",
  VENTA_VITRINA = "VENTA_VITRINA",
  ENTREGA_JOYA = "ENTREGA_JOYA",
  ABONO = "ABONO",
  MOV_ENTRE_CAJA = "MOV_ENTRE_CAJA",
  APERTURA_CAJA = "APERTURA_CAJA",
  CIERRE_CAJA = "CIERRE_CAJA",
  COMPRA_PLAZO_ADENDUM ="COMPRA_PLAZO_ADENDUM",
  DEVOLUCION_GARANTIA = "DEVOLUCION DE GARANTIA",

  CREDITO_NUEVO = "CREDITO NUEVO",
  CREDITO_DEVUELTO = "CREDITO DEVUELTO",
  NOVACION = "NOVACION",
  RETANQUEO = "RETANQUEO"
}