export enum ProcesoEnum {
  //Valores que se usan actualmente 9/Junio/2020 
  //@Twelve
  COTIZACION = "COTIZACION",
	COTIZACION_CONTACT_CENTER = "COTIZACION CONTACT CENTER",
  NEGOCIACION = "NEGOCIACION",
  DATOS_CLIENTE ="DATOS CLIENTE",
	APROBACION = "APROBACION",
	SOLICITUD_DE_GARANTIA = "SOLICITUD DE GARANTIA",
	ENTREGA_DE_GARANTIA = "ENTREGA DE GARANTIA", 
	PAGOS = "PAGOS"
}