export enum PulicidadEnum {
   REDES_SOCIALES='REDES_SOCIALES',
    WEB = 'WEB',
    REFERIDO = 'REFERIDO',
    CLIENTE_QUSKI ='CLIENTE_QUSKI',
    VOLANTEO = 'VOLANTEO',
    RADIO = 'RADIO',
    MUPI = 'MUPI'

}