
export enum TareaEnum { 
    COTIZACCION = "COTIZACCION",
    NEGOCIACION = "NEGOCIACION",
    GESTION_CLIENTE = "GESTION CLIENTE",
    GENERAR_CREDITO = "GENERAR CREDITO",
    APROBACION_EXCEPCION_CLIENTE = "APROBACION EXCEPCION CLIENTE",
    APROBACION_EXCEPCION_RIESGO = "APROBACION EXCEPCION RIESGO",
    APROBACION_EXCEPCION_COBERTURA = "APROBACION EXCEPCION COBERTURA",
    APROBACION_CREDITO = "APROBACION CREDITO"
}