export enum TipoDocumentoEnum {
	COMPRA_PLAZO="COMPRA_PLAZO",
	COMPRA_DIRECTA="COMPRA_DIRECTA",
	CONTRATO_CANCELAR="CONTRATO_CANCELAR",
	CONTRATO_PERFECCIONAR="CONTRATO_PERFECCIONAR",
	CONTRATO_RENOVAR="CONTRATO_RENOVAR",
	VENTA_LOTE="VENTA_LOTE",
	VENTA_VITRINA="VENTA_VITRINA",
	DEVOLVER_JOYA="DEVOLVER_JOYA",
	COMPRA_PLAZO_ADENDUM = "COMPRA_PLAZO_ADENDUM"
}