export enum UsuarioEnum {
    ASESOR = "ASESOR",
	QUSKI = "QUSKI",
	BPM = "BPM",
	BRE = "BRE",
	QUSKI_GAF = "QUSKI GAF",
	QUSKI_ORO = "QUSKI ORO",
	CONTACT_CENTER = "CONTACT CENTER",
	APROBADOR = "APROBADOR",
	FABRICA = "FABRICA",
	MAIL = "MAIL",
	VERIFICADOR_TELEFONICO = "VERIFICADOR TELEFONICO",	
	VPM = "VPM"
}